### ISSUE TITLE
/ce book not work

### ISSUE THREAD

**Issue by KazuyaMNF** [kicjow/Crazy-Enchantments#111] opened 2016-11-16 19:26 UTC
/ce book not work . it says an internal error occured

**Comment by kicjow** [comment] 2016-11-16 21:38
Please go into console and pastebin the error and then post the link here.

**Comment by KazuyaMNF** [comment] 2016-11-17 05:08
[13:03:35] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'ce' in plugin CrazyEnchantments v1.7.0.2
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-e4d4710-e1ebe52]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-e4d4710-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot.jar:git-Spigot-e4d4710-e1ebe52]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot.jar:git-Spigot-e4d4710-e1ebe52]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot.jar:git-Spigot-e4d4710-e1ebe52]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-e4d4710-e1ebe52]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-e4d4710-e1ebe52]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-e4d4710-e1ebe52]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-Spigot-e4d4710-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot.jar:git-Spigot-e4d4710-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-e4d4710-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-e4d4710-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-e4d4710-e1ebe52]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
	at me.BadBones69.CrazyEnchantments.Main.onCommand(Main.java:549) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-e4d4710-e1ebe52]
	... 15 more

**Comment by KazuyaMNF** [comment] 2016-11-17 05:09
This is  short ill force put in here. : P

**Comment by Yukun99** [comment] 2016-11-17 10:34
It's a NullPointerException, you probably left something blank in your configs. Go check again.

**Comment by kicjow** [comment] 2016-11-17 13:04
@KazuyaMNF it seems the problem is your missing this line in the Messages.yml.
https://github.com/kicjow/Crazy-Enchantments/blob/18ebabda4e4ccd8eabb57a430aa91aa4869a74a8/Messages.yml#L32

**Comment by Yukun99** [comment] 2016-11-17 14:27
Yay bad to the rescue :3

**Comment by kicjow** [comment] 2016-11-23 00:25
Please close this if this fixes the problem.

**Comment by KazuyaMNF** [comment] 2016-11-23 13:41
tnk u . 
closed

**Comment by KazuyaMNF** [comment] 2016-11-23 13:41
wait.. how to close :3

**Comment by kicjow** [comment] 2016-11-23 16:54
Please pastebin the error in console.

**Closed** 2016-11-29 03:04 UTC
