### ISSUE TITLE
ERROR Could not pass event EntityDamageByEntityEvent 

### ISSUE THREAD

**Issue by alien4rmspace** [kicjow/Crazy-Enchantments#26] opened 2016-05-27 09:36 UTC
I've been getting this recently

27.05 05:17:53 [Server] ERROR Could not pass event EntityDamageByEntityEvent to CrazyEnchantments v1.6.2.1
27.05 05:17:50 [Server] INFO Caused by: java.lang.NullPointerException
27.05 05:17:50 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_77]
27.05 05:17:50 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot_1.9.2_e000104-4cb3258.jar:git-Spigot-e000104-4cb3258]
27.05 05:17:50 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot_1.9.2_e000104-4cb3258.jar:git-Spigot-e000104-4cb3258]
27.05 05:17:50 [Server] INFO at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot_1.9.2_e000104-4cb3258.jar:git-Spigot-e000104-4cb3258]
27.05 05:17:50 [Server] INFO at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:792) [spigot_1.9.2_e000104-4cb3258.jar:git-Spigot-e000104-4cb3258]
27.05 05:17:50 [Server] INFO at net.minecraft.server.v1_9_R1.WorldServer.tickEntities(WorldServer.java:630) [spigot_1.9.2_e000104-4cb3258.jar:git-Spigot-e000104-4cb3258]
27.05 05:17:50 [Server] INFO at net.minecraft.server.v1_9_R1.World.tickEntities(World.java:1421) [spigot_1.9.2_e000104-4cb3258.jar:git-Spigot-e000104-4cb3258]
27.05 05:17:50 [Server] INFO at net.minecraft.server.v1_9_R1.World.g(World.java:1587) [spigot_1.9.2_e000104-4cb3258.jar:git-Spigot-e000104-4cb3258]
27.05 05:17:50 [Server] INFO at net.minecraft.server.v1_9_R1.World.entityJoinedWorld(World.java:1612) [spigot_1.9.2_e000104-4cb3258.jar:git-Spigot-e000104-4cb3258]
27.05 05:17:50 [Server] INFO at net.minecraft.server.v1_9_R1.EntityTippedArrow.m(EntityTippedArrow.java:68) [spigot_1.9.2_e000104-4cb3258.jar:git-Spigot-e000104-4cb3258]
27.05 05:17:50 [Server] INFO at net.minecraft.server.v1_9_R1.EntityArrow.m(EntityArrow.java:188) [spigot_1.9.2_e000104-4cb3258.jar:git-Spigot-e000104-4cb3258]
27.05 05:17:50 [Server] INFO at net.minecraft.server.v1_9_R1.EntityArrow.a(EntityArrow.java:268) [spigot_1.9.2_e000104-4cb3258.jar:git-Spigot-e000104-4cb3258]
27.05 05:17:50 [Server] INFO at net.minecraft.server.v1_9_R1.EntityPlayer.damageEntity(EntityPlayer.java:497) [spigot_1.9.2_e000104-4cb3258.jar:git-Spigot-e000104-4cb3258]
27.05 05:17:50 [Server] INFO at net.minecraft.server.v1_9_R1.EntityHuman.damageEntity(EntityHuman.java:763) [spigot_1.9.2_e000104-4cb3258.jar:git-Spigot-e000104-4cb3258]
27.05 05:17:50 [Server] INFO at net.minecraft.server.v1_9_R1.EntityLiving.damageEntity(EntityLiving.java:816) [spigot_1.9.2_e000104-4cb3258.jar:git-Spigot-e000104-4cb3258]
27.05 05:17:50 [Server] INFO at net.minecraft.server.v1_9_R1.EntityHuman.damageEntity0(EntityHuman.java:839) [spigot_1.9.2_e000104-4cb3258.jar:git-Spigot-e000104-4cb3258]
27.05 05:17:50 [Server] INFO at net.minecraft.server.v1_9_R1.EntityLiving.damageEntity0(EntityLiving.java:1211) [spigot_1.9.2_e000104-4cb3258.jar:git-Spigot-e000104-4cb3258]
27.05 05:17:50 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:602) [spigot_1.9.2_e000104-4cb3258.jar:git-Spigot-e000104-4cb3258]
27.05 05:17:50 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:479) [spigot_1.9.2_e000104-4cb3258.jar:git-Spigot-e000104-4cb3258]
27.05 05:17:50 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:570) [spigot_1.9.2_e000104-4cb3258.jar:git-Spigot-e000104-4cb3258]
27.05 05:17:50 [Server] INFO at org.bukkit.craftbukkit.v1_9_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:89) [spigot_1.9.2_e000104-4cb3258.jar:git-Spigot-e000104-4cb3258]
27.05 05:17:50 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot_1.9.2_e000104-4cb3258.jar:git-Spigot-e000104-4cb3258]
27.05 05:17:50 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot_1.9.2_e000104-4cb3258.jar:git-Spigot-e000104-4cb3258]
27.05 05:17:50 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot_1.9.2_e000104-4cb3258.jar:git-Spigot-e000104-4cb3258]
27.05 05:17:50 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot_1.9.2_e000104-4cb3258.jar:git-Spigot-e000104-4cb3258]
27.05 05:17:50 [Server] INFO org.bukkit.event.EventException

**Comment by Yukun99** [comment] 2016-05-27 09:57
Doesn't look like an error with CrazyEnchants tbh, try updating spigot?

**Comment by kicjow** [comment] 2016-05-27 12:54
Is this the whole error. If so can you maybe try and see if you can find out whats making this happen. Check the bow enchantments maybe. See if this error happen with them.

**Comment by Yukun99** [comment] 2016-05-29 09:49
I also have this error now, bow enchants just straight out not work.

**Comment by kicjow** [comment] 2016-05-30 08:29
I have tested and not got a error. Please explain how this error is happening. If you don't know then maybe try and find out. @Yukun99 my enchantments are working.

**Comment by Yukun99** [comment] 2016-05-30 09:02
Alright I'll go check again

**Comment by Yukun99** [comment] 2016-05-30 09:37
My server is running into issues, I'll go check after the server resumes and I update to the latest version :P

**Comment by Yukun99** [comment] 2016-05-31 01:12
Found the bug :D
`[09:12:03 ERROR]: Could not pass event EntityDamageByEntityEvent to CrazyEnchantments v1.6.2.3org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[server.jar:git-Spigot-db6de12-18fbb24]	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-db6de12-18fbb24]	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [server.jar:git-Spigot-db6de12-18fbb24]	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [server.jar:git-Spigot-db6de12-18fbb24]	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:87) [server.jar:git-Spigot-db6de12-18fbb24]	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:553) [server.jar:git-Spigot-db6de12-18fbb24]	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:466) [server.jar:git-Spigot-db6de12-18fbb24]	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:585) [server.jar:git-Spigot-db6de12-18fbb24]	at net.minecraft.server.v1_8_R3.EntityLiving.d(EntityLiving.java:1102) [server.jar:git-Spigot-db6de12-18fbb24]	at net.minecraft.server.v1_8_R3.EntityLiving.damageEntity(EntityLiving.java:743) [server.jar:git-Spigot-db6de12-18fbb24]	at net.minecraft.server.v1_8_R3.EntityMonster.damageEntity(EntityMonster.java:42) [server.jar:git-Spigot-db6de12-18fbb24]	at net.minecraft.server.v1_8_R3.EntityArrow.t_(EntityArrow.java:242) [server.jar:git-Spigot-db6de12-18fbb24]	at net.minecraft.server.v1_8_R3.World.entityJoinedWorld(World.java:1607) [server.jar:git-Spigot-db6de12-18fbb24]	at net.minecraft.server.v1_8_R3.World.g(World.java:1582) [server.jar:git-Spigot-db6de12-18fbb24]	at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1425) [server.jar:git-Spigot-db6de12-18fbb24]	at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:597) [server.jar:git-Spigot-db6de12-18fbb24]	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:786) [server.jar:git-Spigot-db6de12-18fbb24]	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [server.jar:git-Spigot-db6de12-18fbb24]	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [server.jar:git-Spigot-db6de12-18fbb24]	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [server.jar:git-Spigot-db6de12-18fbb24]	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]Caused by: java.lang.NullPointerException	at me.BadBones69.CrazyEnchantments.Enchantments.Bows.onArrowLand(Bows.java:146) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[server.jar:git-Spigot-db6de12-18fbb24]	... 20 more`

**Comment by Yukun99** [comment] 2016-05-31 01:12
me.BadBones69.CrazyEnchantments.Enchantments.Bows.onArrowLand(Bows.java:146)

**Comment by Yukun99** [comment] 2016-05-31 01:13
Was just shooting a creeper btw

**Comment by kicjow** [comment] 2016-06-01 05:07
Should be fixed in the next update.

**Closed by kicjow** 2016-06-01 05:07 UTC

**Comment by Yukun99** [comment] 2016-06-01 12:07
Sank yew!
