### ISSUE TITLE
Changing GUI Slots

### ISSUE THREAD

**Issue by KingRaptor345** [kicjow/Crazy-Enchantments#67] opened 2016-07-24 11:31 UTC
Hello!  I am trying to set up my /ce gui to be 1 row of 9 with success dust in the first slot, fixing dust on the 9th, white scroll on the 2nd, and black scroll on the 8th with Tier 1 on the 4th, tier 2 on the 5th, and tier 3 on the 6th.  When I try to do /ce reload it says "An internal error occured while attempting to perform this command."  This is my config.  What is wrong?  [http://pastebin.com/AzbpVvYj](url)

**Comment by kicjow** [comment] 2016-07-24 22:56
Hello the problem is on line number 194. You put Tier1 in a slot that doesn't exist.
Slot: 12 #The Slot number the item will be in

**Closed** 2016-07-25 01:06 UTC
