### ISSUE TITLE
Console Spam every Movement i make with Enchants applied.

### ISSUE THREAD

**Issue by Dazza2206** [kicjow/Crazy-Enchantments#244] opened 2017-08-20 03:34 UTC
[04:24:03 ERROR]: Could not pass event PlayerMoveEvent to CrazyEnchantments v1.7.9.3
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[PaperSpigot.jar:git-PaperSpigot-"4c7641d"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[PaperSpigot.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PaperSpigot.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [PaperSpigot.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [PaperSpigot.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:273) [PaperSpigot.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:126) [PaperSpigot.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [PaperSpigot.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [PaperSpigot.jar:git-PaperSpigot-"4c7641d"]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_144]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_144]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [PaperSpigot.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [PaperSpigot.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [PaperSpigot.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [PaperSpigot.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [PaperSpigot.jar:git-PaperSpigot-"4c7641d"]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
Caused by: java.lang.NullPointerException
        at me.badbones69.crazyenchantments.multisupport.Support$SupportedPlugins.isPluginLoaded(Support.java:241) ~[?:?]
        at me.badbones69.crazyenchantments.enchantments.Armor.onMovement(Armor.java:457) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor31.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_144]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_144]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[PaperSpigot.jar:git-PaperSpigot-"4c7641d"]
        ... 16 more

**Comment by kicjow** [comment] 2017-08-20 03:36
What faction plugin are you using?

**Comment by Dazza2206** [comment] 2017-08-20 03:37
FactionsPlus i'm sure

**Comment by kicjow** [comment] 2017-08-20 03:38
Ah, well CE doesn't support it but that's fine. The problem is how I am handling checking faction plugins. Thanks for the report. It is being fixed now and will be posted in a bit.

**Comment by Dazza2206** [comment] 2017-08-20 03:39
Would you recommend a Factions plugin?

**Comment by kicjow** [comment] 2017-08-20 03:40
I don't know which faction plugins are best but CE does support Factions by MassiveCraft, FactionsUUID, and Legacy Factions.

**Comment by Dazza2206** [comment] 2017-08-20 03:40
Ok thank you very much :)

**Comment by kicjow** [comment] 2017-08-20 03:41
Bug has been fixed and is being posted in a few minutes.

**Closed by kicjow** 2017-08-20 03:41 UTC
Labels: bug

**Comment by kicjow** [comment] 2017-09-22 03:15
![](https://github.trello.services/images/mini-trello-icon.png) [Console Spam every Movement i make with Enchants applied.](https://trello.com/c/3btw2BSw/8-console-spam-every-movement-i-make-with-enchants-applied)
